name: CI/CD 📝

on:
  schedule:
    - cron: "55 3 * * *"
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - setup.py
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Wheel cp${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [38, 39, 310, 311, 312]

    steps:
    - uses: actions/checkout@v3
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.15.0
      env:
        CIBW_BUILD: cp${{ matrix.python }}-manylinux_x86_64
        CIBW_ARCHS_LINUX: auto
        CIBW_TEST_SKIP: "*_aarch64, *macosx*, *_arm64, *_universal2:arm64"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: romantools-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1
