name: CI/CD 📝

on:
  schedule:
    - cron: "55 3 * * *"
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - setup.py
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Wheel cp${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [39, 310, 311, 312]

    steps:
    - uses: actions/checkout@v4
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel

    - name: Build wheels
      run: pip wheel -w DEST_DIR .

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: romantools-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1
